spring:
  datasource:
    url: TBD
    username: kioskdb_admin
    password: password
    driver-class-name: oracle.jdbc.driver.OracleDriver
  flyway:
    user: kioskdb_admin
    password: password
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  application:
    name: KioskApp

server:
  port: 5000
